<?php
defined('ABSPATH') || exit;

/**
 * Automates the seeding of Arabic string translations into Polylang's MO database.
 */
function alsalam_seed_arabic_translations() {
    if (!class_exists('PLL_MO') || !function_exists('PLL')) {
        return ['success' => false, 'message' => 'Polylang is not active.'];
    }

    $polylang = PLL();
    if (empty($polylang->model)) {
        return ['success' => false, 'message' => 'Polylang model not initialized.'];
    }

    // Get the Arabic language object
    $language = $polylang->model->get_language('ar');
    if (!$language) {
        return ['success' => false, 'message' => 'Arabic language not found in Polylang.'];
    }

    // Prepare dictionary (Massive AI-translated collection)
    $arabic_dict = [
        'Request Inquiry' => 'طلب استفسار',
        'Back to Top' => 'العودة للأعلى',
        'All Rights Reserved.' => 'جميع الحقوق محفوظة.',
        'Designed & Developed by' => 'تصميم وتطوير',
        'Read More' => 'اقرأ المزيد',
        'View All' => 'عرض الكل',
        'Contact Us' => 'اتصل بنا',
        'Full Name' => 'الاسم الكامل',
        'Email Address' => 'البريد الإلكتروني',
        'Phone Number' => 'رقم الهاتف',
        'Subject' => 'الموضوع',
        'Message' => 'الرسالة',
        'Send Message' => 'إرسال الرسالة',
        'Sending...' => 'جاري الإرسال...',
        'Company Name' => 'اسم الشركة',
        'Product of Interest' => 'المنتج المطلوب',
        'Submit Inquiry' => 'إرسال الاستفسار',
        'Thank you! Your message has been sent successfully.' => 'شكراً لك! تم إرسال رسالتك بنجاح.',
        'Something went wrong. Please try again.' => 'حدث خطأ ما. يرجى المحاولة مرة أخرى.',
        'All' => 'الكل',
        'Latest' => 'الأحدث',
        'Educational' => 'تعليمي',
        'Office' => 'المكتب',
        'Factory' => 'المصنع',
        'News & Events' => 'الأخبار والفعاليات',
        'Our Products' => 'منتجاتنا',
        'Our Infrastructure' => 'بنيتنا التحتية',
        'What Our Partners Say' => 'ماذا يقول شركاؤنا',
        'Get in touch with us for any inquiries or collaborations.' => 'تواصل معنا لأي استفسارات أو شراكات.',
        'Learn More' => 'اعرف المزيد',
        'About Us' => 'من نحن',
        'About AL-SALAM' => 'نبذة عن السلام',
        'AL-SALAM Pharmaceutical Industry is a sterile manufacturing facility specializing in parenteral solutions, built according to European GMP standards in Iraq.' => 'مصنع شركة السلام للصناعات الدوائية هو منشأة تصنيع معقمة متخصصة في المحاليل الوريدية، تم إنشاؤها وفقاً لمعايير التصنيع الجيد GMP الأوروبية في العراق.',
        'Advanced Sterile Manufacturing' => 'تصنيع معقم متطور',
        'Quality & Laboratory Control' => 'مراقبة الجودة والمختبرات',
        'We combine advanced production, strict quality control, and fully controlled cleanroom environments to ensure safe and reliable pharmaceutical products.' => 'نحن نجمع بين تقنيات الإنتاج المتقدمة والمراقبة الصارمة للجودة وبيئات الغرف النظيفة لضمان تقديم منتجات دوائية آمنة وموثوقة.',
        'Corporate Video Placeholder' => 'مكان الفيديو التعريفي',
        'In production, this overlay will inject an asynchronous high-fidelity HTML5 video player stream or modern iframe embed (e.g., YouTube/Vimeo).' => 'في بيئة الإنتاج، سيقوم هذا التراكب بعرض مشغل فيديو HTML5 عالي الجودة أو إطار iframe حديث (مثل YouTube/Vimeo).',
        'Advanced <span class="text-teal-500">Pharmaceutical</span> Infrastructure' => 'بنية تحتية <span class="text-teal-500">دوائية</span> متطورة',
        'Built on Quality. Driven by Care' => 'مبني على الجودة. مدفوع بالرعاية',
        'Sterile Production' => 'الإنتاج المعقم',
        'Manufactured under strict <strong>GMP</strong> guidelines with high sterility standards to ensure product purity.' => 'تم التصنيع تحت إرشادات <strong>GMP</strong> صارمة بمعايير تعقيم عالية لضمان نقاء المنتج.',
        'Quality Control' => 'مراقبة الجودة',
        'Rigorous testing and analytical inspection to ensure full <strong>compliance</strong> with global pharmacopeia standards.' => 'اختبارات صارمة وفحص تحليلي لضمان <strong>الامتثال</strong> الكامل لمعايير دستور الأدوية العالمي.',
        'Facility & Utilities' => 'المرفق والمرافق العامة',
        'State-of-the-art cleanroom facilities powered by intelligent climate control <strong>(HVAC)</strong> systems.' => 'مرافق غرف نظيفة متطورة مدعومة بأنظمة التحكم في المناخ الذكية <strong>(HVAC)</strong>.',
        'Storage & Packaging' => 'التخزين والتعبئة',
        'Advanced packaging and validation protocols including thermal processing <strong>(autoclave)</strong> for maximum safety.' => 'بروتوكولات تغليف وتحقق متقدمة تشمل المعالجة الحرارية <strong>(الأوتوكلاف)</strong> لأقصى درجات الأمان.',
        'Flexible IV Bag Technology' => 'تكنولوجيا الأكياس الوريدية المرنة',
        'A transversal vision with infinite solutions' => 'رؤية شاملة وحلول لا حصر لها',
        'Safer, Smarter <span class="text-teal-500">Infusion Solutions</span>' => '<span class="text-teal-500">حلول تسريب</span> أكثر أماناً وذكاءً',
        'Advanced flexible IV bags designed to improve safety, handling, and efficiency compared to conventional glass bottles.' => 'أكياس وريدية مرنة ومتطورة مصممة لتحسين السلامة والتعامل والكفاءة مقارنة بالزجاجات الزجاجية التقليدية.',
        'Enhanced Safety' => 'سلامة معززة',
        'Reduced risk of breakage and contamination in clinical settings.' => 'تقليل مخاطر الكسر والتلوث في البيئات السريرية.',
        'Better Handling' => 'تعامل أفضل',
        'Lightweight and easy to transport, optimizing logistics.' => 'خفيفة الوزن وسهلة النقل، مما يحسن العمليات اللوجستية.',
        'Clinical Efficiency' => 'كفاءة سريرية',
        'Streamlined design for medical staff and fast setup.' => 'تصميم مبسط للطاقم الطبي وسرعة التحضير.',
        'Advanced Materials' => 'مواد متطورة',
        'Multi-layered technology for optimal medical protection.' => 'تكنولوجيا متعددة الطبقات لتوفير حماية طبية مثالية.',
        '<span class="text-teal-500">Excellence</span> <br/>in Parenteral Manufacturing' => '<span class="text-teal-500">التميز</span> <br/>في صناعة المحاليل الوريدية',
        'Enter your email...' => 'أدخل بريدك الإلكتروني...',
        'Quick Access' => 'وصول سريع',
        'Services' => 'الخدمات',
        'Parenteral Mfg' => 'تصنيع المحاليل الوريدية',
        'R&D' => 'البحث والتطوير',
        'Resources' => 'المصادر',
        'Careers' => 'الوظائف',
        'Terms of Service' => 'شروط الخدمة',
        'Rules & Regulations' => 'القواعد واللوائح',
        'Privacy Policy' => 'سياسة الخصوصية',
        'European Standards, Iraqi Excellence' => 'معايير أوروبية، تميز عراقي',
        'All Photos' => 'جميع الصور',
        'All Comments' => 'جميع الآراء',
        'AL-SALAM' => 'السلام',
        'Home' => 'الرئيسية',
        'Why Choose Us' => 'لماذا تختارنا',
        'About Us | AL-SALAM Pharmaceutical Industry' => 'من نحن | مصنع السلام للصناعات الدوائية',
        'Learn more about AL-SALAM, a sterile manufacturing facility specializing in parenteral solutions built according to European GMP standards.' => 'تعرف على المزيد حول السلام، منشأة تصنيع معقمة متخصصة في المحاليل الوريدية تم إنشاؤها وفقاً لمعايير GMP الأوروبية.',
        'Pioneering parenteral solution manufacturing with uncompromising clinical excellence and European GMP standards.' => 'رواد في تصنيع المحاليل الوريدية بتميز سريري لا يضاهى ومعايير GMP أوروبية.',
        'Corporate Profile' => 'ملف الشركة',
        'Pioneering Parenteral Solution Manufacturing' => 'ريادة في تصنيع المحاليل الوريدية',
        'AL-SALAM Pharmaceutical Industry stands as a beacon of clinical excellence and manufacturing innovation in Iraq. Specialized in formulation and production of critical sterile parenteral fluids, our facility was engineered from the ground up to conform with the absolute latest European GMP guidelines and global pharmacopeial benchmarks.' => 'تعتبر شركة السلام للصناعات الدوائية منارة للتميز السريري والابتكار الصناعي في العراق. مصنعنا متخصص في صياغة وإنتاج المحاليل الوريدية المعقمة الحيوية، وقد تم تصميمه بالكامل ليتوافق مع أحدث إرشادات ممارسات التصنيع الجيد GMP الأوروبية والمعايير القياسية العالمية للدستور الدوائي.',
        'By combining high-level automated production processes with strict sterile cleanroom environments, AL-SALAM supplies critical hospital networks and public healthcare channels with reliable, high-purity, life-saving intravenous therapeutic systems. We commit to a process where safety margins and chemical sterility are non-negotiable.' => 'من خلال الجمع بين عمليات الإنتاج الآلي المتقدمة وبيئات الغرف النظيفة المعقمة بصرامة، توفر شركة السلام لشبكات المستشفيات الحيوية وقنوات الرعاية الصحية العامة حلولاً علاجية وريدية موثوقة ونقية لإنقاذ الأرواح. نحن ملتزمون بعملية تكون فيها هوامش الأمان والتعقيم الكيميائي غير قابلة للمساومة.',
        'Global Standards Alignment' => 'التوافق مع المعايير العالمية',
        'Fully compliant with the latest United States and European Pharmacopeias (USP/EP).' => 'متوافق تماماً مع أحدث دساتير الأدوية الأمريكية والأوروبية (USP/EP).',
        'Aseptic Automation' => 'أتمتة معقمة',
        'Continuous Blow-Fill-Seal (BFS) integration minimizing human contamination risks.' => 'دمج مستمر لتقنية النفخ والتعبئة والختم (BFS) لتقليل مخاطر التلوث البشري.',
        'Our <span class="text-teal-500">Purpose</span> & Commitments' => '<span class="text-teal-500">أهدافنا</span> والتزاماتنا',
        'Our Vision' => 'رؤيتنا',
        'To position AL-SALAM as the absolute benchmark for sterile pharmaceutical operations within the regional healthcare ecosystem, setting new standards of clinical confidence and safety margins.' => 'ترسيخ مكانة السلام كمرجع رئيسي لعمليات التصنيع الدوائي المعقم ضمن النظام الصحي الإقليمي، مع وضع معايير جديدة للثقة السريرية وهوامش الأمان.',
        'Lead through Quality' => 'الريادة من خلال الجودة',
        'Our Mission' => 'رسالتنا',
        'To manufacture life-saving parenteral therapies under strict GMP protocols, guaranteeing that each vial and infusion meets the highest safety indexes to protect the health of critical patients.' => 'تصنيع محاليل وريدية منقذة للحياة بموجب بروتوكولات GMP الصارمة، لضمان تلبية كل عبوة لأعلى مؤشرات الأمان وحماية صحة الحالات الحرجة.',
        'Protect & Restore Health' => 'حماية واستعادة الصحة',
        'Our Values' => 'قيمنا',
        '<strong>Uncompromising Sterility</strong>: Cleanrooms Class A/B.' => '<strong>تعقيم مطلق</strong>: غرف نظيفة فئة A/B.',
        '<strong>Total Integrity</strong>: Continuous compliance testing.' => '<strong>نزاهة تامة</strong>: اختبارات امتثال مستمرة.',
        '<strong>Technological Focus</strong>: Fully automated aseptic processing.' => '<strong>تركيز تكنولوجي</strong>: معالجة معقمة مؤتمتة بالكامل.',
        'Safety is Our Culture' => 'السلامة هي ثقافتنا',
        'Capabilities' => 'القدرات',
        'Our Advanced Facility Standards' => 'معايير منشأتنا المتطورة',
        'AL-SALAM operations rely on dynamic architectural cleanrooms and premium sterile systems to ensure zero safety compromises.' => 'تعتمد عمليات السلام على غرف نظيفة ذات تصميم ديناميكي وأنظمة تعقيم متميزة لضمان عدم المساومة على السلامة.',
        'Class A/B' => 'فئة A/B',
        'Cleanroom Environment' => 'بيئة الغرف النظيفة',
        'Highly controlled, filtered air space to completely eliminate product contamination.' => 'مساحة هواء مفلترة خاضعة لرقابة صارمة للتخلص تماماً من تلوث المنتج.',
        '100%' => '100%',
        'Aseptic Processing' => 'المعالجة المعقمة',
        'Fully closed sterile lines using computerized safety checks and validation.' => 'خطوط معقمة مغلقة بالكامل باستخدام فحوصات أمان وحسابات مؤتمتة.',
        'HVAC' => 'التدفئة والتهوية وتكييف الهواء (HVAC)',
        'Climate Engineering' => 'هندسة المناخ',
        'Intelligent temperature, humidity, and differential pressure regulation systems.' => 'أنظمة ذكية لتنظيم درجات الحرارة والرطوبة وفروق الضغط.',
        'EU-GMP' => 'ممارسات التصنيع الجيد الأوروبية (EU-GMP)',
        'Regulatory Standard' => 'المعيار التنظيمي',
        'Engineered to strictly conform to European good manufacturing practice standards.' => 'مصمم ليتوافق بدقة مع معايير ممارسات التصنيع الجيد الأوروبية.',
        'Have a business inquiry?' => 'هل لديك استفسار تجاري؟',
        'Products Portfolio | AL-SALAM Pharmaceutical Industry' => 'محفظة المنتجات | مصنع السلام للصناعات الدوائية',
        'Our Sterile <span class="text-transparent bg-clip-text bg-gradient-to-r from-primary-light to-teal-300">Portfolio</span>' => '<span class="text-transparent bg-clip-text bg-gradient-to-r from-primary-light to-teal-300">محفظة منتجاتنا</span> المعقمة',
        'Explore our range of high-quality parenteral therapies and electrolyte solutions manufactured to global regulatory standards.' => 'استكشف مجموعتنا من العلاجات الوريدية ومحاليل الإلكتروليت عالية الجودة المصنعة وفقاً للمعايير التنظيمية العالمية.',
        'Electrolyte Solutions' => 'محاليل الإلكتروليت',
        'Sterile Fluids' => 'السوائل المعقمة',
        'Engineered for absolute chemical stability and sterility' => 'مصمم لتحقيق استقرار كيميائي وتعقيم مطلق',
        'Every parenteral product leaving the AL-SALAM cleanrooms undergoes a rigorous multi-phase validation process to ensure alignment with standard pharmacopeial indexes.' => 'يخضع كل منتج وريدي يغادر غرف السلام النظيفة لعملية تحقق صارمة متعددة المراحل لضمان التوافق مع المؤشرات الدوائية القياسية.',
        'Automatic Blow-Fill-Seal (BFS) technology' => 'تقنية النفخ والتعبئة والختم (BFS) الآلية',
        'Continuous end-to-end parametric monitoring' => 'مراقبة بارامترية مستمرة من البداية للنهاية',
        'Class A terminal sterilization processes' => 'عمليات التعقيم النهائي من الفئة A',
        'Zero Contamination Policy' => 'سياسة خلو التلوث',
        'Closed-loop sterile air showers and pressurized airlocks isolate BFS lines from personnel interference.' => 'غرف هواء معقمة ذات حلقة مغلقة وأقفال هوائية مضغوطة لعزل خطوط BFS عن التداخل البشري.',
        'Iraqi MOH Certified' => 'معتمد من وزارة الصحة العراقية',
        'Strict adherence to Iraqi Ministry of Health requirements alongside international pharmacopeias.' => 'التزام صارم بمتطلبات وزارة الصحة العراقية إلى جانب دساتير الأدوية الدولية.',
        'News & Events | AL-SALAM Pharmaceutical Industry' => 'الأخبار والفعاليات | مصنع السلام للصناعات الدوائية',
        'Stay updated with the latest clinical developments, corporate announcements, and educational resources from AL-SALAM.' => 'ابق على اطلاع بأحدث التطورات السريرية، وإعلانات الشركة، والموارد التعليمية من السلام.',
        'Stay informed about our latest clinical milestones, technical advancements, and health updates.' => 'ابق على اطلاع بأحدث الإنجازات السريرية والتطورات التقنية والتحديثات الصحية.',
        'Featured News' => 'أخبار مميزة',
        'Featured' => 'مميز',
        'Read Featured Article' => 'اقرأ المقال المميز',
        'All Updates' => 'جميع التحديثات',
        'Latest News' => 'أحدث الأخبار',
        'Contact Us | AL-SALAM Pharmaceutical Industry' => 'اتصل بنا | مصنع السلام للصناعات الدوائية',
        'Get in touch with AL-SALAM. Find our facility location, phone numbers, email addresses, and send us a direct message.' => 'تواصل مع السلام. ابحث عن موقع منشأتنا وأرقام الهواتف وعناوين البريد الإلكتروني وأرسل لنا رسالة مباشرة.',
        'Get in <span class="text-transparent bg-clip-text bg-gradient-to-r from-primary-light to-teal-300">Touch</span>' => '<span class="text-transparent bg-clip-text bg-gradient-to-r from-primary-light to-teal-300">تواصل</span> معنا',
        'Have questions about our sterile manufacturing capabilities, product distribution, or regulatory compliance? Reach out to our teams.' => 'هل لديك أسئلة حول قدرات التصنيع المعقم لدينا، أو توزيع المنتجات، أو الامتثال التنظيمي؟ تواصل مع فرقنا.',
        'Our Facility' => 'مرفقنا',
        'AL-SALAM Pharmaceutical Plant, Industrial Zone, Baghdad, Iraq.' => 'مصنع السلام للصناعات الدوائية، المنطقة الصناعية، بغداد، العراق.',
        'Call Us Direct' => 'اتصل بنا مباشرة',
        'Our customer support and clinical representatives are available.' => 'ممثلو خدمة العملاء والممثلون الطبيون متاحون لخدمتك.',
        'Email Channels' => 'قنوات البريد الإلكتروني',
        'Drop us a message and our specialists will respond within 24 hours.' => 'أرسل لنا رسالة وسيرد عليك أخصائيونا في غضون 24 ساعة.',
        'Shift Schedules' => 'أوقات العمل',
        'Our offices are active during corporate weekdays.' => 'مكاتبنا نشطة خلال أيام العمل الرسمية.',
        'Sun - Thu: 8:00 AM - 4:00 PM' => 'الأحد - الخميس: 8:00 صباحاً - 4:00 مساءً',
        'Closed on Friday & Saturday' => 'مغلق يومي الجمعة والسبت',
        'Message Us' => 'راسلنا',
        'Send a Direct Message' => 'إرسال رسالة مباشرة',
        'Please complete the form below. Our corporate relations team will route your inquiry to the appropriate medical or commercial specialist.' => 'يرجى إكمال النموذج أدناه. وسيقوم فريق العلاقات المؤسسية بتوجيه استفسارك إلى الاختصاصي الطبي أو التجاري المناسب.',
        'Interactive Center' => 'المركز التفاعلي',
        'Clinical Logistics' => 'اللوجستيات السريرية',
        'Direct shipping corridors connecting to critical hospital supply lines.' => 'ممرات شحن مباشرة تتصل بخطوط الإمداد الحيوية للمستشفيات.',
        'Co-ordinates' => 'الإحداثيات الجغرافية',
        'GMP Zone' => 'منطقة GMP',
        'Class A Certified' => 'معتمد فئة A',
        'Thank you! Your message has been sent successfully to the AL-SALAM relations team.' => 'شكراً لك! تم إرسال رسالتك بنجاح إلى فريق علاقات السلام.',
        'Request Inquiry | AL-SALAM Pharmaceutical Industry' => 'طلب استفسار | مصنع السلام للصناعات الدوائية',
        'Submit a formal clinical or commercial inquiry. Select products, specify packaging volumes, and upload credentials for quick onboarding.' => 'إرسال استفسار سريري أو تجاري رسمي. حدد المنتجات، وحدد أحجام التعبئة، وحمّل بيانات الاعتماد للبدء السريع.',
        'Company Name *' => 'اسم الشركة *',
        'Al-Rafidain Health Distributors' => 'موزعو صحة الرافدين',
        'Operating Country *' => 'بلد التشغيل *',
        'Iraq' => 'العراق',
        'Representative Name *' => 'اسم المندوب *',
        'Dr. Ahmed Ali' => 'د. أحمد علي',
        'Job Title / Role *' => 'المسمى الوظيفي / الدور *',
        'Procurement Director' => 'مدير المشتريات',
        'Direct Phone *' => 'رقم الهاتف المباشر *',
        '+964 770 123 4567' => '+964 770 123 4567',
        'Website URL' => 'رابط الموقع الإلكتروني',
        'Proceed to Step 2' => 'المضي قدماً إلى الخطوة 2',
        'Inquiry Type *' => 'نوع الاستفسار *',
        'Select option...' => 'اختر...',
        'Hospital / Clinic Distribution' => 'توزيع للمستشفيات / العيادات',
        'Contract Aseptic BFS Manufacturing' => 'تصنيع معقم تعاقدي (BFS)',
        'Chemical / API Sterile Sourcing' => 'توريد مواد فعالة معقمة',
        'Regulatory Compliance / Dossiers' => 'الامتثال التنظيمي / الملفات',
        'General Commercial Partnerships' => 'شراكات تجارية عامة',
        'Select product...' => 'اختر المنتج...',
        'Multiple Products / General Order' => 'منتجات متعددة / طلب عام',
        'Estimated Annual Volume Needs (Units)' => 'الاحتياجات السنوية التقديرية (وحدات)',
        'e.g. 500,000 infusion bottles' => 'مثال: 500,000 زجاجة تسريب',
        'Clinical Specs / Message *' => 'المواصفات السريرية / الرسالة *',
        'Outline formulation requirements, special packaging specs, or delivery terms...' => 'حدد متطلبات التركيب، أو مواصفات التغليف الخاصة، أو شروط التسليم...',
        'Back to Step 1' => 'العودة إلى الخطوة 1',
        'Submit B2B Inquiry' => 'إرسال استفسار تجاري',
        'Please fill out all required fields marked with * on Step 1.' => 'يرجى ملء جميع الحقول المطلوبة المميزة بـ * في الخطوة 1.',
        'Fill out your credentials below. Our HR and talent acquisition team will evaluate your clinical or technical experience for relevant vacancies.' => 'املأ بياناتك أدناه. سيقوم فريق الموارد البشرية والتوظيف بتقييم خبرتك السريرية أو الفنية للوظائف الشاغرة المناسبة.',
        'Enter your email address' => 'أدخل بريدك الإلكتروني',
        'AL-SALAM Pharmaceutical Industry is a sterile manufacturing facility...' => 'مصنع شركة السلام للصناعات الدوائية هو منشأة تصنيع معقمة...',
        'Copyright © [year] AL-SALAM. All rights reserved.' => 'حقوق الطبع والنشر © [year] السلام. جميع الحقوق محفوظة.',
        'We combine advanced production, strict quality control...' => 'نحن نجمع بين تقنيات الإنتاج المتقدمة والمراقبة الصارمة للجودة...',
        
        // Items from previous seeder iterations
        '36 Months from packaging date' => '36 شهراً من تاريخ التعبئة',
        '2. Clinical Inquiry' => '2. الاستفسار السريري',
        'Location:' => 'الموقع:',
        'Facility' => 'المنشأة',
        'Submit formal product distribution requests, cleanroom API sourcing, or contract manufacturing proposals directly to our operations.' => 'قدم طلبات التوزيع الرسمية للمنتجات، أو مصادر المواد الفعالة في الغرف النظيفة، أو مقترحات التصنيع التعاقدي مباشرة إلى عملياتنا.',
        'Thank you! Your career application has been submitted to the AL-SALAM HR team.' => 'شكراً لك! تم تقديم طلب التوظيف الخاص بك إلى فريق الموارد البشرية في السلام.',
        'Careers Intake' => 'استقبال طلبات التوظيف',
        'Join a world-class team of sterile manufacturing specialists, pharmaceutical engineers, and clinical professionals dedicated to setting new benchmarks in Iraq.' => 'انضم إلى فريق عالمي من المتخصصين في التصنيع المعقم، والمهندسين الصيدلانيين، والمهنيين السريريين المكرسين لوضع معايير جديدة في العراق.',
        'Clinical Overview' => 'نظرة عامة سريرية',
        'Volume Availability' => 'الأحجام المتوفرة',
        'Quality Grade' => 'درجة الجودة',
        'European Standards Approved' => 'معتمد وفق المعايير الأوروبية',
        'Metric Details' => 'التفاصيل المترية',
        'European Union GMP Class A Filling Standards' => 'معايير التعبئة فئة A حسب ممارسات التصنيع الجيد للاتحاد الأوروبي',
        'Products' => 'المنتجات',
        '1. Business Profile' => '1. الملف التجاري',
        'Tested & validation-indexed for therapeutic hospital networks.' => 'تم اختباره وفهرسته لشبكات المستشفيات العلاجية.',
        'Every batch undergoes real-time parametric release testing to ensure compliance.' => 'تخضع كل دفعة لاختبار الإصدار البارامترى في الوقت الفعلي لضمان الامتثال.',
        'Aseptic Validation' => 'التحقق المعقم',
        'Our BFS parenteral formulations undergo 100% automated particulate and pyrogen testing to ensure zero contamination across critical supply chains.' => 'تخضع تركيباتنا المعقمة لاختبارات آلية بنسبة 100% للجسيمات والمواد المسببة للحمى لضمان عدم وجود تلوث عبر سلاسل التوريد الحرجة.',
        'Packaging presentation' => 'شكل العبوة',
        'Clinical Inquiry Details' => 'تفاصيل الاستفسار السريري',
        'Thank you! Your commercial inquiry has been registered. Our procurement team will review your business credentials.' => 'شكراً لك! تم تسجيل استفسارك التجاري. سيقوم فريق المشتريات لدينا بمراجعة بيانات الاعتماد التجارية الخاصة بك.',
        'Pages:' => 'الصفحات:',
        'Stability & Sterility Assurance' => 'ضمان الاستقرار والعقم',
        'Gallery' => 'المعرض',
        'Specification Parameter' => 'معلمة المواصفات',
        'High Thermal & Chemical Stability Packaging' => 'تغليف ذو استقرار حراري وكيميائي عالي',
        'Product Formulation & Intent' => 'تركيبة المنتج والغرض منه',
        'Submit Application' => 'تقديم الطلب',
        'Related <span class="text-teal-500">Parenteral</span> Formulations' => 'تركيبات <span class="text-teal-500">معقمة</span> ذات صلة',
        'Automated Leak Testing & Pyrogen Controls' => 'اختبار التسرب الآلي وضوابط البيروجين',
        'Commercial & Business Profile' => 'الملف التجاري والأعمال',
        'Specify your clinical requests, products of interest, and volume demands.' => 'حدد طلباتك السريرية، والمنتجات ذات الاهتمام، ومتطلبات الحجم.',
        'Please provide credential details for clinical vetting and registration.' => 'يرجى تقديم تفاصيل الاعتماد للتدقيق السريري والتسجيل.',
        'Work Culture & Growth' => 'ثقافة العمل والنمو',
        'Why Build Your Career with AL-SALAM?' => 'لماذا تبني مستقبلك المهني مع السلام؟',
        'Full CTD/eCTD dossier availability for hospital registration and tenders.' => 'توفر ملف CTD/eCTD الكامل لتسجيل المستشفيات والمناقصات.',
        'Regulatory Dossiers' => 'الملفات التنظيمية',
        'Request Commercial Inquiry' => 'طلب استفسار تجاري',
        'Photographer:' => 'المصور:',
        'Build your career with Iraq\'s leading sterile pharmaceutical manufacturer. We offer opportunities across R&D, clinical QA, engineering, and commercial operations.' => 'ابنِ مستقبلك المهني مع الشركة الرائدة في تصنيع الأدوية المعقمة في العراق. نحن نقدم فرصاً في البحث والتطوير، وضمان الجودة السريرية، والهندسة، والعمليات التجارية.',
        'Take a look inside our sterile cleanroom operations, high-tech BFS processing systems, and microbiological laboratories.' => 'ألقِ نظرة داخل عمليات غرفنا النظيفة المعقمة، وأنظمة المعالجة عالية التقنية، والمختبرات الميكروبيولوجية.',
        'Article Details' => 'تفاصيل المقال',
        'Submit Your Profile' => 'أرسل ملفك الشخصي',
        'Explore our comprehensive portfolio of European GMP certified sterile infusion solutions, parenteral electrolytes, and specialized APIs.' => 'استكشف محفظتنا الشاملة من محاليل التسريب المعقمة المعتمدة وفق ممارسات التصنيع الجيد الأوروبية، والإلكتروليتات، والمواد الفعالة المتخصصة.',
        'Search Results for: %s' => 'نتائج البحث عن: %s',
        'Previous' => 'السابق',
        'Next' => 'التالي',
        
        // HTML snippets
        'Our <span class="text-transparent bg-clip-text bg-gradient-to-r from-primary-light to-teal-300">Products</span>' => 'منتجات<span class="text-transparent bg-clip-text bg-gradient-to-r from-primary-light to-teal-300">نا</span>',
        'Join <span class="text-transparent bg-clip-text bg-gradient-to-r from-primary-light to-teal-300">Our Team</span>' => 'انضم إلى <span class="text-transparent bg-clip-text bg-gradient-to-r from-primary-light to-teal-300">فريقنا</span>',
        'Company <span class="text-transparent bg-clip-text bg-gradient-to-r from-primary-light to-teal-300">Gallery</span>' => 'معرض <span class="text-transparent bg-clip-text bg-gradient-to-r from-primary-light to-teal-300">الشركة</span>',
        'Request <span class="text-transparent bg-clip-text bg-gradient-to-r from-primary-light to-teal-300">Inquiry</span>' => 'طلب <span class="text-transparent bg-clip-text bg-gradient-to-r from-primary-light to-teal-300">استفسار</span>',
        'Related <span class="text-teal-500">News</span> &amp; Updates' => 'أخبار <span class="text-teal-500">وتحديثات</span> ذات صلة',

        // New missing strings from Hero/Homepage features
        'Delivering high-quality parenteral solutions conforming to global regulatory frameworks with state-of-the-art sterile processing facilities. All lines operate with automated aseptic safety protocols.' => 'تقديم محاليل وريدية عالية الجودة مطابقة للأطر التنظيمية العالمية مع أحدث مرافق المعالجة المعقمة. تعمل جميع الخطوط ببروتوكولات أمان معقمة آلية.',
        'Utilizing advanced barrier systems (RABS) and blow-fill-seal methodologies to eliminate intervention vectors, ensuring the absolute highest safety indexes in parenteral formulation.' => 'استخدام أنظمة الحواجز المتقدمة ومنهجيات النفخ والتعبئة والختم لضمان أعلى مؤشرات السلامة في التركيبات الوريدية.',
        'Supplying life-saving intravenous solutions and vial parenterals globally. Our robust supply channels secure critical hospital networks with seamless therapeutic solutions continuous-uptime assurance.' => 'توريد المحاليل الوريدية المنقذة للحياة على مستوى العالم. قنوات التوريد القوية لدينا تؤمن شبكات المستشفيات الحيوية بحلول علاجية سلسة.',
        'Manufactured under strict GMP guidelines with high sterility standards to ensure product purity.' => 'تم التصنيع وفقاً لإرشادات GMP الصارمة بمعايير تعقيم عالية لضمان نقاء المنتج.',
        'Rigorous testing and analytical inspection to ensure full compliance with global pharmacopeia standards.' => 'اختبارات صارمة وفحص تحليلي لضمان الامتثال الكامل لمعايير دستور الأدوية العالمي.',
        'State-of-the-art cleanroom facilities powered by intelligent climate control (HVAC) systems.' => 'مرافق غرف نظيفة متطورة مدعومة بأنظمة التحكم في المناخ الذكية (HVAC).',
        'Advanced packaging and validation protocols including thermal processing for maximum safety.' => 'بروتوكولات التغليف والتحقق المتقدمة بما في ذلك المعالجة الحرارية لأقصى درجات الأمان.',
        'The professionalism and quality of sterile solutions provided by AL-SALAM have completely elevated our hospital operations. Their supply consistency is unmatched.' => 'لقد أدت احترافية وجودة المحاليل المعقمة التي تقدمها السلام إلى الارتقاء بعمليات المستشفى بالكامل. اتساق الإمداد لديهم لا مثيل له.',
        'Fantastic experience with their flexible IV bag line. Light, durable, and highly compliant with global pharmacopoeial standards. Highly recommended.' => 'تجربة رائعة مع خط أكياس الحقن الوريدي المرنة. خفيفة ومتينة ومتوافقة للغاية مع معايير دستور الأدوية العالمي. نوصي بها بشدة.',
        'A truly reliable partner for critical care fluids in Iraq. Their compliance with European GMP standards is clear in every batch they deliver.' => 'شريك موثوق حقاً لسوائل العناية المركزة في العراق. امتثالهم لمعايير GMP الأوروبية واضح في كل دفعة يقدمونها.',
        'Copyright © ٢٠٢٦ AL-SALAM. All rights reserved.' => 'حقوق الطبع والنشر © ٢٠٢٦ السلام. جميع الحقوق محفوظة.',
        'Copyright © 2026 AL-SALAM. All rights reserved.' => 'حقوق الطبع والنشر © 2026 السلام. جميع الحقوق محفوظة.',
        'Standards' => 'المعايير',
        'EU-GMP Certified' => 'معتمد من EU-GMP',
        'Open in Maps' => 'فتح في الخرائط',
        'AL-SALAM Plant' => 'مصنع السلام',
        'Baghdad, Iraq' => 'بغداد، العراق',
        'European GMP Standards' => 'معايير GMP الأوروبية',
        'Work alongside international pharmaceutical standards in state-of-the-art Class A/B cleanroom facilities.' => 'العمل وفقاً للمعايير الصيدلانية الدولية في أحدث مرافق الغرف النظيفة من الفئة A/B.',
        'Clinical Development' => 'التطوير السريري',
        'Structured career progression tracks, continuous aseptic technology workshops, and leadership mentorship.' => 'مسارات تقدم مهني منظمة، وورش عمل مستمرة حول تقنيات التعقيم، وإرشاد قيادي.',
        'Cutting-Edge Tech' => 'تقنيات متطورة',
        'Operate fully automated Blow-Fill-Seal (BFS) lines and computerized parametric quality assurance systems.' => 'تشغيل خطوط النفخ والتعبئة والختم (BFS) الآلية بالكامل وأنظمة ضمان الجودة البارامترية المحوسبة.',
        'Life-Saving Purpose' => 'هدف منقذ للحياة',
        'Be part of a mission supplying essential Parenteral therapies to critical hospital networks across the nation.' => 'كن جزءاً من مهمة توفير العلاجات الوريدية الأساسية لشبكات المستشفيات الحيوية في جميع أنحاء البلاد.',
        
        // Dynamic Customizer Arrays (Hero Slides, Marquee, etc.)
        'COMPANY' => 'الشركة',
        'Manufacturing Built on European GMP Standards' => 'تصنيع مبني على معايير التصنيع الجيد (GMP) الأوروبية',
        'TECHNOLOGY' => 'التكنولوجيا',
        'Advanced Aseptic Lines' => 'خطوط معقمة متطورة',
        'High-Tech Bio-Processing Operations' => 'عمليات معالجة حيوية عالية التقنية',
        'HEALTHCARE' => 'الرعاية الصحية',
        'Global Core Logistics' => 'خدمات لوجستية عالمية أساسية',
        'Reliable Essential Critical-Care Distribution' => 'توزيع موثوق لأساسيات العناية المركزة',
        'Trusted Quality' => 'جودة موثوقة',
        'European Standards' => 'معايير أوروبية',
        'GMP Certified' => 'معتمد من GMP',
        'Advanced Technology' => 'تكنولوجيا متطورة',

        // Single Theme Mods & Exact Testimonial Strings
        'Ahmed Yassin' => 'أحمد ياسين',
        'Clinical Director' => 'مدير سريري',
        'Pharmacist Sarah Rafiq' => 'الصيدلانية سارة رفيق',
        'Procurement Manager' => 'مدير المشتريات',
        'Mustafa Jawad' => 'مصطفى جواد',
        'Critical Care Specialist' => 'أخصائي العناية المركزة',
        'Reliable Sterile Solutions' => 'محاليل معقمة موثوقة',
        'Advanced <span class="text-teal-500">Pharmaceutical</span> Infrastructure' => 'بنية تحتية <span class="text-teal-500">دوائية</span> متطورة',
        'Built on Quality. Driven by Care' => 'مبنية على الجودة. مدفوعة بالرعاية',
        'All Products' => 'جميع المنتجات',
        'Company Gallery' => 'معرض الشركة',
        'View All' => 'عرض الكل',
        'Flexible IV Bag Technology' => 'تكنولوجيا الأكياس الوريدية المرنة',
        'Why Choose Us' => 'لماذا تختارنا',
        'Safer, Smarter <span class="text-teal-500">Infusion Solutions</span>' => 'حلول تسريب <span class="text-teal-500">أكثر أماناً وذكاءً</span>',
        'News & Events' => 'أخبار وفعاليات',
        'Read More' => 'اقرأ المزيد',
        'What Our Partners Say' => 'ماذا يقول شركاؤنا',
        'All Comments' => 'جميع التعليقات',
        'Page Not Found' => 'الصفحة غير موجودة',
        'Back to Home' => 'العودة للرئيسية',
        'About AL-SALAM' => 'نبذة عن السلام',
        'Corporate Profile' => 'ملف الشركة',
        'Learn More' => 'اعرف المزيد',
        'About Us' => 'من نحن',
        'Our Products' => 'منتجاتنا',
        'Excellence <br/> in Parenteral Manufacturing' => 'التميز <br/> في التصنيع الوريدي'
    ];

    // Merge with old dictionary to ensure nothing is missed
    $old_data = @include ALSALAM_DIR . '/includes/translations-data.php';
    if (isset($old_data['ar']) && isset($old_data['en'])) {
        $reverse_dict = [];
        foreach ($old_data['en'] as $slug => $en_string) {
            if (isset($old_data['ar'][$slug])) {
                $reverse_dict[$en_string] = $old_data['ar'][$slug];
            }
        }
        $arabic_dict = array_merge($reverse_dict, $arabic_dict);
    }

    // Import current strings from DB
    $mo = new PLL_MO();
    $mo->import_from_db($language);

    // Track added translations
    $added_count = 0;

    // We only update if we have an Arabic translation for an English string
    foreach ($arabic_dict as $english_string => $arabic_translation) {
        if (!empty($arabic_translation) && !empty($english_string)) {
            $mo->add_entry($mo->make_entry($english_string, $arabic_translation));
            $added_count++;
        }
    }

    // Save back to database
    $mo->export_to_db($language);

    // Call Polylang action if necessary
    do_action('pll_save_strings_translations');

    return ['success' => true, 'message' => "Successfully injected $added_count Arabic string translations into Polylang DB."];
}
